USB_VID = 0x239A
USB_PID = 0x811E

USB_PRODUCT = "Feather ESP32-S3 TFT"
USB_MANUFACTURER = "Adafruit"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

# OPTIMIZATION_FLAGS = -Os
CIRCUITPY_ESPCAMERA = 0
